#!/bin/bash

# Liste der Repo-URLs
REPO_LIST=(
    "http://poomsmart.github.io/repo/"
)

for REPO_URL in "${REPO_LIST[@]}"; do
    # Repo-Name aus URL erzeugen (nur alphanumerisch und Unterstriche)
    REPO_NAME=$(echo "$REPO_URL" \
        | sed 's#^https\?://##' \
        | sed 's#/$##' \
        | sed 's/[^a-zA-Z0-9]/_/g')

    # Quelle mit Architektur für iOS 6 anlegen
    echo "deb [arch=iphoneos-arm] $REPO_URL ./" \
        > "/etc/apt/sources.list.d/${REPO_NAME}.list"
done

# Cydia-Quellen aktualisieren
apt-get update

exit 0